
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
// #include <stdint.h>



static const uint8_t image_data_circle_Image[16] = {
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc3, 0xbd, 0x7e, 0x7e, 0x7e, 0x7e, 0xbd, 0xc3, 0xff, 0xff

};

static const uint8_t image_data_clear_Image[16] = {
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff

};

static const uint8_t image_data_bar_Image[16] = {
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    // ∙
    // ∙
    // █
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xe1, 
    0xe1, 
    0xff, 
    0xc1, 
    0xc1, 
    0xff, 
    0x81, 
    0x81, 
    0xff, 
    0x01, 
    0x01, 
    0xff
};
// const tImage Image = { image_data_Image, 16, 8,
//     8 };

